### ISSUE TITLE
[Bug]: Specification 4 Not Fully Implemented

### ISSUE THREAD

**Issue by stef-rausch** [chrisgrieser/obsidian-sembr#1]
### Bug Description

"A semantic line break must occur after a sentence, as punctuated by a period (.), exclamation mark (!), or question mark (?)."

Exclamation marks and question marks are not considered for inserting a semantic line break.

Keep up the good work.

### Relevant Screenshot

https://user-images.githubusercontent.com/1460531/169386988-8e5ebb98-bdc6-4519-8f63-cfe586b099f3.MOV

### To Reproduce

Use the following test text and toggle the semantic line breaks:

What is a semantic line break? When writing text with a compatible markup language, add a line break after each substantial unit of thought. That's it! In a nutshell.

### Obsidian Version

Mobile Insider: 1.2.2 (53) -- API v0.14.11

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by stef-rausch** [comment]
Thanks!

**Comment by chrisgrieser** [comment]
thanks for the bug report. I worried so much about edge cases like footnotes at the end of a sentence, that I totally forgot `?!–` 🙈
