### ISSUE TITLE
Feature Request: Option to Honour Semantic Break Lines Without Trailing Space

### ISSUE THREAD

**Issue by stef-rausch** [chrisgrieser/obsidian-sembr#4]
### Feature Requested

Currently the plugin does only recognise semantic breaks if there is a trailing space on the respective lines.

I suggest to offer an option to allow both a [ single ] `SPACE\n` and a `\n` after the last identifier -- as per specification no. 4 and 5 -- or word on the line. It makes it fool-proof while writing semantically.

Thank you for considering.

### Relevant Screenshot

https://user-images.githubusercontent.com/1460531/169402781-12ee33f1-5838-41eb-8b2f-94cf66b38113.mp4

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
actually, I have thought about it and it makes sense to stich lines back together even if they do not have a trailing whitespace at the end.

so now the plugin will convert them back either way

**Comment by stef-rausch** [comment]
Thanks!
