### ISSUE TITLE
[Bug]: toggling back breaks quotes/callouts

### ISSUE THREAD

**Issue by kometenstaub** [chrisgrieser/obsidian-sembr#5]
### Bug Description

The plugin doesn‘t handle multiline quotes/callouts correctly.

### To Reproduce

1. Have a note with quotes/callouts that span multiple lines.
2. Toggle semantic line breaks, toggle back.
3. They will look like this:
   ```
   > text > second line > third line
   ```

### Obsidian Version

0.14.11

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
fixed in latest release
